FROM balenalib/raspberrypi3-debian:bullseye

WORKDIR /app

ENV DEBIAN_FRONTEND noninteractive

RUN sudo apt-get update  && sudo apt-get install -y \
    build-essential \
    python3-dev \
    python3-pip \
    python3-setuptools \
    swig \
    zlib1g-dev \
    gcc \
    mono-mcs \ 
    libgpiod2 \
    python3-rpi.gpio


RUN sudo pip3 install --upgrade pip
COPY requirements.txt ./
RUN sudo pip3 install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]